version: "3"
services:
        mariadb:
                build: ./requirements/mariadb
                container_name: mariadb
                restart: always
                env_file: 
                        - .env
                volumes:
                        - db-files:/var/lib/mysql
                networks:
                        - samati

        wordpress:
                build: ./requirements/wordpress
                container_name: wordpress
                volumes:
                        - wp-files:/var/www/html
                depends_on:
                        - mariadb
                restart: always
                networks:
                        - samati

        nginx:
                build: ./requirements/nginx
                container_name: nginx
                ports:
                        - 443:443
                restart: always
                volumes:
                        - wp-files:/var/www/html
                depends_on:
                        - wordpress
                networks:
                        - samati
networks:
        samati:
                driver: bridge

volumes:
        db-files:
                driver: local
                driver_opts:
                  type: 'none'
                  o: 'bind'
                  device: '/home/escanor/data/mysql'
        wp-files:
                driver: local
                driver_opts:
                        type: 'none'
                        o: 'bind'
                        device: '/home/escanor/data/html'